##########################
POST http://127.0.0.1:3000/auth/forgot-password
Content-Type: application/json

{
    "email":"jcc.toaso@yavirac.edu.ec"
    
}

############
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpjYy50b2Fzb0B5YXZpcmFjLmVkdS5lYyIsImlhdCI6MTczMzg5MzYxMywiZXhwIjoxNzMzODk3MjEzfQ.dgmiCxaocBo-eZv3j0awWbKARoQlBGsOqw6nMmN046o",
  "newPassword": "1234567"
}